---
- name: installeer en update servers
  hosts: all
  become: true

  tasks:
    - name: update pakket lijst
      apt:
        update_cache: yes
        force_apt_get: yes

- name: configureer webserver
  hosts: webserver
  become: true
  tasks:
    - name: installeer apache en php
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - php
        - libapache2-mod-php

    - name: start en zet apache aan
      systemd:
        name: apache2
        state: started
        enabled: true

    - name: upload php demo bestand
      copy:
        src: ~/demo-website/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'

- name: configureer database server
  hosts: dbserver
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: installeer mariadb en python mysql modules
      apt:
        name:
          - mariadb-server
          - python3-pymysql
        state: present

    - name: start en zet mariadb aan
      systemd:
        name: mariadb
        state: started
        enabled: true